### ISSUE TITLE
add semver/semantic release on main

### ISSUE THREAD

**Issue by amber-beasley-liatrio** [liatrio/gh-trusted-builds-workflows#157]
https://liatrio.slack.com/archives/C04U86KTERJ/p1725557995014699?thread_ts=1725557675.508559&cid=C04U86KTERJ

**Comment by ianhundere** [comment]
ah, was going to do this in https://github.com/liatrio/demo-gh-autogov-workflows/issues/11 / will mention this in PR to close this tomorrow
