### ISSUE TITLE
remove need for personal access token for release creation

### ISSUE THREAD

**Issue by amber-beasley-liatrio** [liatrio/gh-trusted-builds-workflows#171]
# Currently 

The instructions for the autogov reusable workflow have the user create a person access token and include access to the current repo (app repo), so that the release can execute.

failed job: https://github.com/liatrio/demo-autogov-hello-world-app/actions/runs/11583046484/job/32247437059

# Ask

Is there a way to eliminate the need to use a personal access token for this?

**Comment by ianhundere** [comment]
i "think" [this](https://github.com/liatrio/demo-gh-autogov-workflows/issues/212) resolved this behavior.
